"""empty message

Revision ID: 371fe236ff18
Revises: 01f2dd459d22
Create Date: 2025-08-20 15:35:57.405721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '371fe236ff18'
down_revision = '01f2dd459d22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('admin_user')
    op.drop_table('friend')
    op.drop_table('promo_code')
    op.drop_table('campaign')
    op.drop_table('task')
    op.drop_table('transaction')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=32), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=8), nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('reward', sa.INTEGER(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=64), nullable=True),
    sa.Column('claimed', sa.BOOLEAN(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('link', sa.VARCHAR(length=255), nullable=True),
    sa.Column('goal', sa.INTEGER(), nullable=True),
    sa.Column('cost', sa.FLOAT(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=64), nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promo_code',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=64), nullable=False),
    sa.Column('type', sa.VARCHAR(length=32), nullable=True),
    sa.Column('value', sa.FLOAT(), nullable=True),
    sa.Column('max_uses', sa.INTEGER(), nullable=True),
    sa.Column('used_by', sa.TEXT(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('friend',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('friend_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('coins', sa.INTEGER(), nullable=True),
    sa.Column('spins', sa.INTEGER(), nullable=True),
    sa.Column('ad_credit', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
